import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/general/themeProvider";
import { TranstackReactQueryProvider } from "@/components/general/transtackReactQueryProvider";
import { ModeToggle } from "@/components/general/modeToggle";
import { Toaster } from "@/components/ui/sonner";
import { LogoutButton } from "@/features/auth/components/logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranstackReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            {children}
            <ModeToggle />
            <LogoutButton
              className="absolute top-4 right-4"
              variant={"outline"}
            >
              Logout
            </LogoutButton>
          </ThemeProvider>
        </TranstackReactQueryProvider>
      </body>
    </html>
  );
}
